export const dbDoc = [
    // { statusType:'2',status:'Barlagda',id: '5', description: 'Harydyň düzüm birligi üçin tassyknama', title: 'Tassyknama', sender: 'Başlyk', file_type: 'doc', file_link: '/docs/Ikramow Atamyrat ylmy iş Täze.docx', limit_date: '7d', send_date: '15/02/2024' },
    // { statusType:'0',status:'Yzyna gaýtarylan',id: '1', description: 'Harytlary geljekde ylalaşykdaky baha esasynda satyn almak boýunça şertnama', title: 'Şertnama', sender: 'Buhgalter', file_type: 'xlsx', file_link: '/docs/test.xlsx', limit_date: '3d', send_date: '13/02/2024' },
    // { statusType:'1',status:'Tassyklanan ',id: '2', description: 'Işe kabul etmeklige arza', title: 'Arza', sender: 'Işgär', file_type: 'xlsx', file_link: '/docs/test.xlsx', limit_date: '4d', send_date: '15/02/2024' },
    // { statusType:'2',status:'Barlagda',id: '3', description: 'Aýyň jemi boýunça hasabat', title: 'Hasabat', sender: 'Orunbasar', file_type: 'pptx', file_link: 'https://docs.google.com/presentation/d/1GP2XUStcFpVPeJPR2Cos4wgvMGSSpd5Q/edit?usp=sharing&ouid=104436693899328402494&rtpof=true&sd=true', limit_date: '2d', send_date: '11/02/2024' },
    // { statusType:'1',status:'Tassyklanan',id: '4', description: 'Harydyň hili boýunça güwanama', title: 'Güwänama', sender: 'Buhgalter', file_type: 'pdf', file_link: '/docs/test2.pdf', limit_date: '1d', send_date: '12/02/2024' },
    // { statusType:'1',status:'Tassyklanan',id: '6', description: 'Harydyň hili boýunça güwanama', title: 'Güwänama', sender: 'Buhgalter', file_type: 'pdf', file_link: '/docs/test2.pdf', limit_date: '1d', send_date: '12/02/2024' },
    // { statusType:'1',status:'Tassyklanan',id: '7', description: 'Harydyň hili boýunça güwanama', title: 'Güwänama', sender: 'Buhgalter', file_type: 'pdf', file_link: '/docs/test2.pdf', limit_date: '1d', send_date: '12/02/2024' },
    // { statusType:'1',status:'Tassyklanan',id: '8', description: 'Harydyň hili boýunça güwanama', title: 'Güwänama', sender: 'Buhgalter', file_type: 'pdf', file_link: '/docs/test2.pdf', limit_date: '1d', send_date: '12/02/2024' },

]